%采用写入文件的方法创建状态转移方程
fprintf(fid,'%s','function F = transfun(x,dt,dx,alpha,beta,lamda,Din,Ppre,Mspre,Ps,Mse)\n');
fprintf(fid,'%s','F = [(alpha*Ps/(1+beta*Ps)+alpha*x(2)/(1+beta*x(2))-alpha*Ppre(1)/(1+beta*Ppre(1))-alpha*Ppre(2)/(1+beta*Ppre(2)))/2/dt + (x(3)+Mspre(2)-x(1)-Mspre(1))/2/dx;\n');
fprintf(fid,'%s','(x(1)+x(3)-Mspre(1)-Mspre(2))/2/dt + (x(3)^2*(1+beta*x(2))/alpha/x(2)+x(2)+Mspre(2)^2*(1+beta*Ppre(2))/alpha/Ppre(2)+Ppre(2)-x(1)^2*(1+beta*Ps)/alpha/Ps-Ps-Mspre(1)^2*(1+beta*Ppre(1))/alpha/Ppre(1)-Ppre(1))/2/dx + lamda*(x(1)^2*(1+beta*Ps)/alpha/Ps+x(3)^2*(1+beta*x(2))/alpha/x(2)+Mspre(1)^2*(1+beta*Ppre(1))/alpha/Ppre(1)+Mspre(2)^2*(1+beta*Ppre(2))/alpha/Ppre(2))/8/Din;\n');
for i = 2:SpaceSteps-1
	fprintf(fid,'%s','(alpha*x(2*i)/(1+beta*x(2*i-2))+alpha*x(2*i)/(1+beta*x(2*i))-alpha*Pressure(i)/(1+beta*Pressure(i))-alpha*Pressure(i+1)/(1+beta*Pressure(i+1)))/2/dt + (x(2*i+1)+MassFlux(i+1)-x(2*i-1)-MassFlux(i))/2/dx;');
	fprintf(fid,'%s','(x(2*i-1)+x(2*i+1)-MassFlux(i)-MassFlux(i+1))/2/dt + ((x(2*i+1)^2)*(1+beta*x(2*i-2))/alpha/x(2*i-2)+x(2*i)+(MassFlux(i+1)^2)*(1+beta*Pressure(i+1))/alpha/Pressure(i+1)+Pressure(i+1)-(x(2*i-1)^2)*(1+beta*x(2*i-2))/alpha/x(2*i-2)-x(2*i-2)-(MassFlux(i)^2)*(1+beta*Pressure(i))/alpha/Pressure(i)-Pressure(i))/2/dx + lamda*((x(2*i+1)^2)*(1+beta*x(2*i-2))/alpha/x(2*i-2)+(MassFlux(i+1)^2)*(1+beta*Pressure(i+1))/alpha/Pressure(i+1)+(x(2*i-1)^2)*(1+beta*x(2*i-2))/alpha/x(2*i-2)+(MassFlux(i)^2)*(1+beta*Pressure(i))/alpha/Pressure(i))/8/Din')
end
fprintf(fid,'%s','(alpha*x(2*SpaceSteps-2)/(1+beta*x(2*SpaceSteps-2))+alpha*x(2*SpaceSteps)/(1+beta*x(2*SpaceSteps))-alpha*Pressure(SpaceSteps)/(1+beta*Pressure(SpaceSteps))-alpha*Pressure(SpaceSteps+1)/(1+Pressure(SpaceSteps+1)))/2/dt + (Mse(1)+MassFlux(SpaceSteps+1)-x(2*SpaceSteps-1)-MassFlux(SpaceSteps))/2/dx;');
fprintf(fid,'%s','x(2*SpaceSteps-1)+Mse(1)-MassFlux(SpaceSteps)-MassFlux(SpaceSteps+1))/2/dt + ((Mse(1)^2)*(1+beta*x(2*SpaceSteps))/alpha/x(2*SpaceSteps)+x(2*SpaceSteps)+(MassFlux(SpaceSteps+1)^2)*(1+beta*Pressure(SpaceSteps+1))/alpha/Pressure(SpaceSteps+1)+Pressure(SpaceSteps+1)-(x(2*i-1)^2)*(1+beta*x(2*SpaceSteps-2))/alpha/x(2*SpaceSteps-2)-x(2*SpaceSteps-2)-(MassFlux(SpaceSteps)^2)*(1+beta*Pressure(SpaceSteps))/alpha/Pressure(SpaceSteps)-Pressure(SpaceSteps-1))/2/dx + lamda*((Mse(1)^2)*(1+beta*x(2*SpaceSteps))/alpha/x(2*SpaceSteps)+(MassFlux(SpaceSteps+1)^2)*(1+beta*Pressure(SpaceSteps+1))/alpha/Pressure(SpaceSteps+1)+(x(2*i-1)^2)*(1+beta*x(2*SpaceSteps-2))/alpha/x(2*SpaceSteps-2)+(MassFlux(SpaceSteps)^2)*(1+beta*Pressure(SpaceSteps))/alpha/Pressure(SpaceSteps))/8/Din];');