%采用写入文件的方法创建状态转移方程
function creat_transfun_re01(SpaceSteps)
	fid = fopen('transfun_re01.m','w');
	fprintf(fid,'%s\n','%状体转移方程');
	fprintf(fid,'\n');
	fprintf(fid,'%s\n','function F = transfun_re01(x,dt,dx,alpha,beta,lamda,Din,Ppre,Mspre,Mss,Mse)');
	fprintf(fid,'\t%s\n','F = [(alpha*x(1)/(1+beta*x(1))+alpha*x(2)/(1+beta*x(2))-alpha*Ppre(1)/(1+beta*Ppre(1))-alpha*Ppre(2)/(1+beta*Ppre(2)))/2/dt + (x(3)+Mspre(2)-Mss-Mspre(1))/2/dx;');
	fprintf(fid,'\t%s\n','(Mss+x(3)-Mspre(1)-Mspre(2))/2/dt + (x(3)^2*(1+beta*x(2))/alpha/x(2)+x(2)+Mspre(2)^2*(1+beta*Ppre(2))/alpha/Ppre(2)+Ppre(2)-Mss^2*(1+beta*x(1))/alpha/x(1)-x(1)-Mspre(1)^2*(1+beta*Ppre(1))/alpha/Ppre(1)-Ppre(1))/2/dx + lamda*(Mss^2*(1+beta*x(1))/alpha/x(1)+x(3)^2*(1+beta*x(2))/alpha/x(2)+Mspre(1)^2*(1+beta*Ppre(1))/alpha/Ppre(1)+Mspre(2)^2*(1+beta*Ppre(2))/alpha/Ppre(2))/8/Din;');
	for i = 2:SpaceSteps-1
		%str = ['(alpha*x(', sprintf('%u', 2*i-2), ')/(1+beta*x(', sprintf('%u', 2*i-2), '))+alpha*x(', sprintf('%u', 2*i), ')/(1+beta*x(', sprintf('%u', 2*i), '))-alpha*Ppre(', sprintf('%u', i), ')/(1+beta*Ppre(', sprintf('%u', i), '))-alpha*Ppre(', sprintf('%u', i+1), ')/(1+beta*Ppre(', sprintf('%u', i+1), ')))/2/dt + (x(', sprintf('%u', 2*i+1), ')+Mspre(', sprintf('%u', i+1), ')-x(', sprintf('%u', 2*i-1), ')-Mspre(', sprintf('%u', i), '))/2/dx;'];
		%str2 = ['(x(' sprintf('%u', 2*i-1) ')+x(' sprintf('%u', 2*i+1) ')-Mspre(' sprintf('%u', i) ')-Mspre(' sprintf('%u', i+1) '))/2/dt + ((x(' sprintf('%u', 2*i+1) ')^2)*(1+beta*x(' sprintf('%u', 2*i) '))/alpha/x(' sprintf('%u', 2*i) ')+x(' sprintf('%u', 2*i) ')+(Mspre(' sprintf('%u', i+1) ')^2)*(1+beta*Ppre(' sprintf('%u', i+1) '))/alpha/Ppre(' sprintf('%u', i+1) ')+Ppre(' sprintf('%u', i+1) ')-(x(' sprintf('%u', 2*i-1) ')^2)*(1+beta*x(' sprintf('%u', 2*i-2) '))/alpha/x(' sprintf('%u', 2*i-2) ')-x(' sprintf('%u', 2*i-2) ')-(Mspre(' sprintf('%u', i) ')^2)*(1+beta*Ppre(' sprintf('%u', i) '))/alpha/Ppre(' sprintf('%u', i) ')-Ppre(' sprintf('%u', i) '))/2/dx + lamda*((x(' sprintf('%u', 2*i+1) ')^2)*(1+beta*x(' sprintf('%u', 2*i) '))/alpha/x(' sprintf('%u', 2*i) ')+(Mspre(' sprintf('%u', i+1) ')^2)*(1+beta*Ppre(' sprintf('%u', i+1) '))/alpha/Ppre(' sprintf('%u', i+1) ')+(x(' sprintf('%u', 2*i-1) ')^2)*(1+beta*x(' sprintf('%u', 2*i-2) '))/alpha/x(' sprintf('%u', 2*i-2) ')+(Mspre(' sprintf('%u', i) ')^2)*(1+beta*Ppre(' sprintf('%u', i) '))/alpha/Ppre(' sprintf('%u', i) '))/8/Din'];
		fprintf(fid,'\t%s\n',['(alpha*x(', sprintf('%u', 2*i-2), ')/(1+beta*x(', sprintf('%u', 2*i-2), '))+alpha*x(', sprintf('%u', 2*i), ')/(1+beta*x(', sprintf('%u', 2*i), '))-alpha*Ppre(', sprintf('%u', i), ')/(1+beta*Ppre(', sprintf('%u', i), '))-alpha*Ppre(', sprintf('%u', i+1), ')/(1+beta*Ppre(', sprintf('%u', i+1), ')))/2/dt + (x(', sprintf('%u', 2*i+1), ')+Mspre(', sprintf('%u', i+1), ')-x(', sprintf('%u', 2*i-1), ')-Mspre(', sprintf('%u', i), '))/2/dx;']);
		fprintf(fid,'\t%s\n',['(x(' sprintf('%u', 2*i-1) ')+x(' sprintf('%u', 2*i+1) ')-Mspre(' sprintf('%u', i) ')-Mspre(' sprintf('%u', i+1) '))/2/dt + (x(' sprintf('%u', 2*i+1) ')^2*(1+beta*x(' sprintf('%u', 2*i) '))/alpha/x(' sprintf('%u', 2*i) ')+x(' sprintf('%u', 2*i) ')+Mspre(' sprintf('%u', i+1) ')^2*(1+beta*Ppre(' sprintf('%u', i+1) '))/alpha/Ppre(' sprintf('%u', i+1) ')+Ppre(' sprintf('%u', i+1) ')-x(' sprintf('%u', 2*i-1) ')^2*(1+beta*x(' sprintf('%u', 2*i-2) '))/alpha/x(' sprintf('%u', 2*i-2) ')-x(' sprintf('%u', 2*i-2) ')-Mspre(' sprintf('%u', i) ')^2*(1+beta*Ppre(' sprintf('%u', i) '))/alpha/Ppre(' sprintf('%u', i) ')-Ppre(' sprintf('%u', i) '))/2/dx + lamda*(x(' sprintf('%u', 2*i-1) ')^2*(1+beta*x(' sprintf('%u', 2*i-2) '))/alpha/x(' sprintf('%u', 2*i-2) ')+x(' sprintf('%u', 2*i+1) ')^2*(1+beta*x(' sprintf('%u', 2*i) '))/alpha/x(' sprintf('%u', 2*i) ')+Mspre(' sprintf('%u', i) ')^2*(1+beta*Ppre(' sprintf('%u', i) '))/alpha/Ppre(' sprintf('%u', i) ')+Mspre(' sprintf('%u', i+1) ')^2*(1+beta*Ppre(' sprintf('%u', i+1) '))/alpha/Ppre(' sprintf('%u', i+1) '))/8/Din;']);
	end
	%str3 = ['(alpha*x(' sprintf('%u', 2*SpaceSteps-2) ')/(1+beta*x(' sprintf('%u', 2*SpaceSteps-2) '))+alpha*x(' sprintf('%u', 2*SpaceSteps) ')/(1+beta*x(' sprintf('%u', 2*SpaceSteps) '))-alpha*Ppre(' sprintf('%u', SpaceSteps) ')/(1+beta*Ppre(' sprintf('%u', SpaceSteps) '))-alpha*Ppre(' sprintf('%u', SpaceSteps+1) ')/(1+Ppre(' sprintf('%u', SpaceSteps+1) ')))/2/dt + (Mse+Mspre(' sprintf('%u', SpaceSteps+1) ')-x(' sprintf('%u', 2*SpaceSteps-1) ')-Mspre(' sprintf('%u', SpaceSteps) '))/2/dx;\n']
	%str4 = ['x(' sprintf('%u', 2*SpaceSteps-1) ')+Mse-Mspre(' sprintf('%u', SpaceSteps) ')-Mspre(' sprintf('%u', SpaceSteps+1) '))/2/dt + ((Mse^2)*(1+beta*x(' sprintf('%u', 2*SpaceSteps) '))/alpha/x(' sprintf('%u', 2*SpaceSteps) ')+x(' sprintf('%u', 2*SpaceSteps) ')+(Mspre(' sprintf('%u', SpaceSteps+1) ')^2)*(1+beta*Ppre(' sprintf('%u', SpaceSteps+1) '))/alpha/Ppre(' sprintf('%u', SpaceSteps+1) ')+Ppre(' sprintf('%u', SpaceSteps+1) ')-(x(' sprintf('%u', 2*SpaceSteps-1) ')^2)*(1+beta*x(' sprintf('%u', 2*SpaceSteps-2) '))/alpha/x(' sprintf('%u', 2*SpaceSteps-2) ')-x(' sprintf('%u', 2*SpaceSteps-2) ')-(Mspre(' sprintf('%u', SpaceSteps) ')^2)*(1+beta*Ppre(' sprintf('%u', SpaceSteps) '))/alpha/Ppre(' sprintf('%u', SpaceSteps) ')-Ppre(' sprintf('%u', SpaceSteps-1) '))/2/dx + lamda*((Mse^2)*(1+beta*x(' sprintf('%u', 2*SpaceSteps) '))/alpha/x(' sprintf('%u', 2*SpaceSteps) ')+(Mspre(' sprintf('%u', SpaceSteps+1) ')^2)*(1+beta*Ppre(' sprintf('%u', SpaceSteps+1) '))/alpha/Ppre(' sprintf('%u', SpaceSteps+1) ')+(x(' sprintf('%u', 2*SpaceSteps-1) ')^2)*(1+beta*x(' sprintf('%u', 2*SpaceSteps-2) '))/alpha/x(' sprintf('%u', 2*SpaceSteps-2) ')+(Mspre(' sprintf('%u', SpaceSteps) ')^2)*(1+beta*Ppre(' sprintf('%u', SpaceSteps) '))/alpha/Ppre(' sprintf('%u', SpaceSteps) '))/8/Din];\n']
	fprintf(fid,'\t%s\n',['(alpha*x(' sprintf('%u', 2*SpaceSteps-2) ')/(1+beta*x(' sprintf('%u', 2*SpaceSteps-2) '))+alpha*x(' sprintf('%u', 2*SpaceSteps) ')/(1+beta*x(' sprintf('%u', 2*SpaceSteps) '))-alpha*Ppre(' sprintf('%u', SpaceSteps) ')/(1+beta*Ppre(' sprintf('%u', SpaceSteps) '))-alpha*Ppre(' sprintf('%u', SpaceSteps+1) ')/(1+beta*Ppre(' sprintf('%u', SpaceSteps+1) ')))/2/dt + (Mse+Mspre(' sprintf('%u', SpaceSteps+1) ')-x(' sprintf('%u', 2*SpaceSteps-1) ')-Mspre(' sprintf('%u', SpaceSteps) '))/2/dx;']);
	fprintf(fid,'\t%s\n',['(x(' sprintf('%u', 2*SpaceSteps-1) ')+Mse-Mspre(' sprintf('%u', SpaceSteps) ')-Mspre(' sprintf('%u', SpaceSteps+1) '))/2/dt + (Mse^2*(1+beta*x(' sprintf('%u', 2*SpaceSteps) '))/alpha/x(' sprintf('%u', 2*SpaceSteps) ')+x(' sprintf('%u', 2*SpaceSteps) ')+Mspre(' sprintf('%u', SpaceSteps+1) ')^2*(1+beta*Ppre(' sprintf('%u', SpaceSteps+1) '))/alpha/Ppre(' sprintf('%u', SpaceSteps+1) ')+Ppre(' sprintf('%u', SpaceSteps+1) ')-x(' sprintf('%u', 2*SpaceSteps-1) ')^2*(1+beta*x(' sprintf('%u', 2*SpaceSteps-2) '))/alpha/x(' sprintf('%u', 2*SpaceSteps-2) ')-x(' sprintf('%u', 2*SpaceSteps-2) ')-Mspre(' sprintf('%u', SpaceSteps) ')^2*(1+beta*Ppre(' sprintf('%u', SpaceSteps) '))/alpha/Ppre(' sprintf('%u', SpaceSteps) ')-Ppre(' sprintf('%u', SpaceSteps) '))/2/dx + lamda*(x(' sprintf('%u', 2*SpaceSteps-1) ')^2*(1+beta*x(' sprintf('%u', 2*SpaceSteps-2) '))/alpha/x(' sprintf('%u', 2*SpaceSteps-2) ')+Mse^2*(1+beta*x(' sprintf('%u', 2*SpaceSteps) '))/alpha/x(' sprintf('%u', 2*SpaceSteps) ')+Mspre(' sprintf('%u', SpaceSteps) ')^2*(1+beta*Ppre(' sprintf('%u', SpaceSteps) '))/alpha/Ppre(' sprintf('%u', SpaceSteps) ')+Mspre(' sprintf('%u', SpaceSteps+1) ')^2*(1+beta*Ppre(' sprintf('%u', SpaceSteps+1) '))/alpha/Ppre(' sprintf('%u', SpaceSteps+1) '))/8/Din;']);
	fprintf(fid,'\t%s','];');
	fclose(fid);